#!/bin/zsh --no-rcs

url="https://YOUR-JAMF-PRO-HERE.jamfcloud.com"
client_id="CLIENTID"
client_secret="CLIENT SECRET"

getAccessToken() {
	response=$(curl --silent --location --request POST "${url}/api/v1/oauth/token" \
		--header "Content-Type: application/x-www-form-urlencoded" \
		--data-urlencode "client_id=${client_id}" \
		--data-urlencode "grant_type=client_credentials" \
		--data-urlencode "client_secret=${client_secret}")
	access_token=$(echo "$response" | plutil -extract access_token raw -)
	token_expires_in=$(echo "$response" | plutil -extract expires_in raw -)
	token_expiration_epoch=$(($current_epoch + $token_expires_in - 1))
}

checkTokenExpiration() {
	current_epoch=$(date +%s)
	if [[ token_expiration_epoch -ge current_epoch ]]
	then
		echo "Token valid until the following epoch time: " "$token_expiration_epoch"
	else
		echo "No valid token available, getting new token"
		getAccessToken
	fi
}

invalidateToken() {
	responseCode=$(curl -w "%{http_code}" -H "Authorization: Bearer ${access_token}" $url/api/v1/auth/invalidate-token -X POST -s -o /dev/null)
	if [[ ${responseCode} == 204 ]]
	then
		echo "Token successfully invalidated"
		access_token=""
		token_expiration_epoch="0"
	elif [[ ${responseCode} == 401 ]]
	then
		echo "Token already invalid"
	else
		echo "An unknown error occurred invalidating the token"
	fi
}

#Run the function to get an access token and then the echo of how much time until it expires in seconds
getAccessToken 
echo "Access token expires in $token_expires_in seconds"

####################################
# START API COMMANDS HERE
####################################

curl -s -H "authorization: Bearer $access_token" -H "accept: application/json" \
"$url/api/v1/computers-inventory/6/attachments" \
-H "content-type: multipart/form-data" \
-F file=@"/var/log/jamf.log;type=text/plain" \
-X 'POST'

####################################
# END API COMMANDS BEFORE THIS LINE
####################################

# Invalidate the access token
invalidateToken 
